title: Mel Chua
email: mel@melchua.com
description: >-
  "Hacker. Writer. Researcher. Teacher. Human jumper cable."
twitter_username: mchua
github_username:  mchua

baseurl: https://caseyg.github.io/melchua

paginate: 25
paginate_path: "/page/:num/"

collections:
  topics:
    output: true
  drawings:
    output: true
  talks:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "topics"
    values:
      permalink: /sketches/:title/
      layout: topic
  -
    scope:
      path: ""
      type: "drawings"
    values:
      permalink: /sketches/drawings/:title/
      layout: default
  -
    scope:
      path: ""
      type: "talks"
    values:
      permalink: /studies/talks/:title/
      layout: default

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
