title: Mel Chua
email: mel@melchua.com
description: >-
  "Hacker. Writer. Researcher. Teacher. Human jumper cable."
twitter_username: mchua
github_username:  mchua

baseurl: http://caseyg.github.io/melchua

paginate: 25
paginate_path: "/page/:num/"

collections:
  topics:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "topics"
    values:
      permalink: /topics/:title/
      layout: topic

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
